[package]
name = "oraclecmd"
version = "1.0.0"
authors = ["planet0104 <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
oracle = { git = "https://github.com/kubo/rust-oracle" }
rust-ini = "*"
prettytable-rs = "*"